CREATE TABLE IF NOT EXISTS bookmark_table (
    item_key INTEGER PRIMARY KEY Generated BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    link text NOT NULL,
    description text,
    rating INTEGER NOT Null
   /* date_added TIMESTAMP DEFAULT now() NOT NULL, */
);
